services:
  - type: web
    name: influencer-ai-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PORT
        value: 10000
buildCommand: pip install --upgrade pip && pip install -r requirements.txt
env:
  - key: PYTHON_VERSION
    value: 3.8.17
